name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk git unzip

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      # Cache Buildozer directories
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.buildozer/android
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Build APK
      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      # Upload APK artifacts
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
