name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Especifica la versión de Python aquí

      # Install Buildozer and dependencies
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          sudo apt-get install -y openjdk-8-jdk

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug

      # Upload artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
